- name: Install kubectl and configure kubeconfig
  hosts: eks-admin-nodes
  become: true

  vars:
    aws_region: us-west-2
    cluster_name: my-eks-o-cluster
    kubectl_version: "v1.29.0"
    aws_access_key_id: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_access_key: "{{ lookup('env', 'AWS_secrect_KEY_ID') }}"

  tasks:
    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - curl
        - unzip
        - apt-transport-https
        - ca-certificates
        - gnupg
        - software-properties-common

    - name: Download kubectl binary from Kubernetes official repo
      get_url:
        url: "https://dl.k8s.io/release/{{ kubectl_version }}/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: Install AWS CLI v2
      unarchive:
        src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp
        remote_src: yes
        creates: /usr/local/bin/aws

    - name: Run AWS CLI installer
      command: /tmp/aws/install
      args:
        creates: /usr/local/bin/aws

    - name: Create AWS credentials directory for root
      file:
        path: /root/.aws
        state: directory
        mode: '0700'

    - name: Configure AWS credentials for root user
      copy:
        dest: /root/.aws/credentials
        content: |
          [default]
          aws_access_key_id={{ aws_access_key_id }}
          aws_secret_access_key={{ aws_secret_access_key }}
        mode: '0600'

    - name: Create kubeconfig for EKS using root's AWS credentials
      shell: >
        aws eks update-kubeconfig --region {{ aws_region }}
        --name {{ cluster_name }}
      register: kubeconfig_output
      changed_when: "'Added new context' in kubeconfig_output.stdout"

    - name: Create .kube directory for ubuntu user
      file:
        path: /home/ubuntu/.kube
        state: directory
        mode: '0755'
        owner: ubuntu
        group: ubuntu

    - name: Copy kubeconfig from root to ubuntu user
      copy:
        src: /root/.kube/config
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Show kubectl context
      command: kubectl config current-context
      register: context_output
      ignore_errors: true

    - name: Debug current context
      debug:
        var: context_output.stdout
