---
# install_kubectl_and_kubeconfig.yml
- name: Install kubectl and configure kubeconfig for EKS
  hosts: eks-admin-nodes
  become: true
  vars:
    aws_region: us-west-2
    cluster_name: my-eks-o-cluster
    kubectl_version: "v1.29.0"
    # These will be passed from Jenkins pipeline or vault
    aws_access_key: "{{ aws_access_key | default(omit) }}"
    aws_secret_key: "{{ aws_secret_key | default(omit) }}"

  tasks:
    - name: Verify AWS credentials are provided
      fail:
        msg: "AWS credentials must be provided through vault or environment variables"
      when: aws_access_key is undefined or aws_secret_key is undefined

    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - curl
        - unzip
        - apt-transport-https
        - ca-certificates
        - gnupg
        - software-properties-common
      tags: packages

    - name: Download kubectl binary
      get_url:
        url: "https://dl.k8s.io/release/{{ kubectl_version }}/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: '0755'
        validate_certs: yes
      tags: kubectl

    - name: Install AWS CLI v2
      block:
        - name: Download AWS CLI
          unarchive:
            src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
            dest: /tmp
            remote_src: yes
            creates: /tmp/aws/dist/aws
          
        - name: Install AWS CLI
          command: /tmp/aws/install
          args:
            creates: /usr/local/bin/aws
          
        - name: Clean up installer
          file:
            path: /tmp/aws
            state: absent
      tags: awscli

    - name: Configure AWS credentials
      block:
        - name: Create AWS config directory
          file:
            path: /root/.aws
            state: directory
            mode: '0700'
          
        - name: Configure credentials file
          copy:
            dest: /root/.aws/credentials
            content: |
              [default]
              aws_access_key_id={{ aws_access_key }}
              aws_secret_access_key={{ aws_secret_key }}
            mode: '0600'
          no_log: true
      tags: aws-config

    - name: Configure kubeconfig for EKS
      shell: |
        aws eks update-kubeconfig \
          --region {{ aws_region }} \
          --name {{ cluster_name }}
      register: kubeconfig_output
      changed_when: "'Added new context' in kubeconfig_output.stdout"
      tags: kubeconfig

    - name: Setup kubectl for ubuntu user
      block:
        - name: Create .kube directory
          file:
            path: /home/ubuntu/.kube
            state: directory
            mode: '0755'
            owner: ubuntu
            group: ubuntu
          
        - name: Copy kubeconfig
          copy:
            src: /root/.kube/config
            dest: /home/ubuntu/.kube/config
            remote_src: yes
            owner: ubuntu
            group: ubuntu
            mode: '0644'
      tags: user-config

    - name: Verify kubectl configuration
      block:
        - name: Get current context
          command: kubectl config current-context
          register: context_output
          ignore_errors: yes
          
        - name: Show current context
          debug:
            msg: "Current kubectl context: {{ context_output.stdout }}"
            verbosity: 1
      tags: verify
